spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/system_test?useSSL=false&serverTimezone=UTC
    username: postgres_user
    password: postgres_pass
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  data:
    rest:
      base-path: /api
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
logging:
  level:
    org:
      springframework: debug